require 'rbconfig'
require 'open-uri'
require 'fileutils'
include FileUtils::Verbose
require 'rake/clean'

version="0.42.3"
URL="https://github.com/pachterlab/kallisto/archive/v#{version}.tar.gz"
path = File.expand_path(File.dirname(__FILE__))
puts path
#path_external = File.join ( path , "../lib/bio/external" )


task :download do
	open(URL) do |uri|
		File.open("v#{version}.tar.gz",'wb') do |fout|
			fout.write(uri.read)
    end #fout 
  end #uri
end

task :compile do
	sh "tar -xzf v#{version}.tar.gz"
	cd ("kallisto-#{version}") do
		mkdir "build"
		cd "build" do
			sh "cmake -DCMAKE_INSTALL_PREFIX:PATH=#{path}/../lib/bio/external .."
			sh "make"
			sh "make install"
		end
	end
end
#task :default => [:download, :compile, :clean]
task :default => [:download, :compile]
